version: "3.9"

services:
  frontend:
    image: node:20
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: sh -c "corepack enable && pnpm install && pnpm nx run frontend:dev --port=3000 --hostname=0.0.0.0"
    ports:
      - "3000:3000"
    env_file: .env

  gateway:
    image: node:20
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: sh -c "corepack enable && pnpm install && PORT=4000 pnpm nx run gateway:serve"
    ports:
      - "4000:4000"
    env_file: .env

  agent:
    image: node:20
    working_dir: /workspace
    volumes:
      - .:/workspace
    command: sh -c "corepack enable && pnpm install && PORT=8001 pnpm nx run agent:serve"
    ports:
      - "8001:8001"
    env_file: .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ossdb
    ports:
      - "5432:5432"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
